seeds: [1]
device: "cpu"
limit: 50          # ~200 requests on HellaSwag
batch_size: 4      # smaller batch size for MPS
num_fewshot: 0

tasks:
  hellaswag:
    lm_eval_id: hellaswag
    metric: acc_norm
